swagger: "2.0"
info:
  description: "API Documentation"
  version: "1.0.0"
  title: "Kuali API"
host: "localhost:5000"
basePath: "/"
schemes:
  - "http"
paths:
  /companies:
    get:
      tags:
        - "Companies"
      summary: "Obtener listado de empresas"
      responses:
        200:
          description: "Lista de empresas"
          schema:
            type: array
            items:
              $ref: "#/definitions/Company"
    post:
      tags:
        - "Companies"
      summary: "Crear una empresa"
      parameters:
        - in: "body"
          name: "body"
          description: "Datos de la empresa a crear"
          required: true
          schema:
            $ref: "#/definitions/CompanyInput"
      responses:
        201:
          description: "Empresa creada"
          schema:
            $ref: "#/definitions/Company"
  /leads:
    get:
      tags:
        - "Leads"
      summary: "Obtener listado de leads"
      responses:
        200:
          description: "Lista de leads"
          schema:
            type: array
            items:
              $ref: "#/definitions/Lead"
    post:
      tags:
        - "Leads"
      summary: "Crear un nuevo lead"
      parameters:
        - in: "body"
          name: "body"
          description: "Datos del lead a crear"
          required: true
          schema:
            $ref: "#/definitions/LeadInput"
      responses:
        201:
          description: "Lead creado"
          schema:
            $ref: "#/definitions/Lead"
  /templates:
    get:
      tags:
        - "Templates"
      summary: "Obtener todas las plantillas"
      responses:
        200:
          description: "Lista de plantillas"
          schema:
            type: array
            items:
              $ref: "#/definitions/Template"
    post:
      tags:
        - "Templates"
      summary: "Crear una plantilla"
      parameters:
        - in: "body"
          name: "body"
          description: "Datos de la plantilla"
          required: true
          schema:
            $ref: "#/definitions/TemplateInput"
      responses:
        201:
          description: "Plantilla creada"
          schema:
            $ref: "#/definitions/Template"
  /contacts:
    get:
      tags:
        - "Contacts"
      summary: "Obtener listado de contactos"
      responses:
        200:
          description: "Lista de contactos"
          schema:
            type: array
            items:
              $ref: "#/definitions/Contact"
    post:
      tags:
        - "Contacts"
      summary: "Crear un contacto"
      parameters:
        - in: "body"
          name: "body"
          description: "Datos del contacto"
          required: true
          schema:
            $ref: "#/definitions/ContactInput"
      responses:
        201:
          description: "Contacto creado"
          schema:
            $ref: "#/definitions/Contact"
definitions:
  Company:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      sector:
        type: string
  CompanyInput:
    type: object
    required:
      - name
    properties:
      name:
        type: string
      sector:
        type: string
  Lead:
    type: object
    properties:
      id:
        type: string
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      phoneNumber:
        type: string
      linkedinUrl:
        type: string
      role:
        type: string
      seniority:
        type: string
      status:
        type: string
      companyId:
        type: string
  LeadInput:
    type: object
    required:
      - firstName
      - lastName
      - email
      - companyId
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
      phoneNumber:
        type: string
      linkedinUrl:
        type: string
      role:
        type: string
      seniority:
        type: string
      companyId:
        type: string
  Template:
    type: object
    properties:
      id:
        type: string
      title:
        type: string
      body:
        type: string
  TemplateInput:
    type: object
    required:
      - title
      - body
    properties:
      title:
        type: string
      body:
        type: string
  Contact:
    type: object
    properties:
      id:
        type: string
      name:
        type: string
      phone:
        type: string
      email:
        type: string
      leadId:
        type: string
      status:
        type: string
  ContactInput:
    type: object
    required:
      - email
    properties:
      name:
        type: string
      phone:
        type: string
      email:
        type: string
      leadId:
        type: string